#!/usr/bin/sh -e

bat_status=$( cat /sys/class/power_supply/BAT1/capacity )
charging_status=$( cat /sys/class/power_supply/BAT1/status )

health() {
    for i in {0..4}
    do
        if [[ $i -le $(( $bat_status/20 )) ]]; then
            echo -ne "#[fg=colour1]• "
        else
            echo -ne "#[fg=colour8]• "
        fi
    done
    echo
}

bat_status_small() {
    if [[ "$charging_status" = *Charging* ]]; then
        echo -ne "+$bat_status"
    else
        echo -ne "$bat_status"
    fi
}

[ -z "$1" ] && {
    bat_status_small
}

while getopts qi options 
do
    case $options in
        i)
            bat_status_small
            ;;
        q)
            if [[ "$charging_status" = *Charging* ]]; then
                echo -ne "+ $(health)"
            else
                health
            fi
    esac
done
